// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoLbdz5Wz_7qJfu-6jvQdCmQ6fYITl6qw',
    appId: '1:808889045331:web:07168e5fba6d86d1b611a6',
    messagingSenderId: '808889045331',
    projectId: 'hw4-3-darsh',
    authDomain: 'hw4-3-darsh.firebaseapp.com',
    storageBucket: 'hw4-3-darsh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAStZRR4wsx6MUqo9PtMI3ak0Udw_CvcPs',
    appId: '1:808889045331:android:9bf4f0ee66ceadccb611a6',
    messagingSenderId: '808889045331',
    projectId: 'hw4-3-darsh',
    storageBucket: 'hw4-3-darsh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYsu8ZhjrQUn6WQ-okXpUFw5GBL7firQ',
    appId: '1:808889045331:ios:3288b7cbd57e74f2b611a6',
    messagingSenderId: '808889045331',
    projectId: 'hw4-3-darsh',
    storageBucket: 'hw4-3-darsh.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWYsu8ZhjrQUn6WQ-okXpUFw5GBL7firQ',
    appId: '1:808889045331:ios:3288b7cbd57e74f2b611a6',
    messagingSenderId: '808889045331',
    projectId: 'hw4-3-darsh',
    storageBucket: 'hw4-3-darsh.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoLbdz5Wz_7qJfu-6jvQdCmQ6fYITl6qw',
    appId: '1:808889045331:web:2f99752ad0d83c87b611a6',
    messagingSenderId: '808889045331',
    projectId: 'hw4-3-darsh',
    authDomain: 'hw4-3-darsh.firebaseapp.com',
    storageBucket: 'hw4-3-darsh.firebasestorage.app',
  );
}
